FROM golang:1.18-alpine3.15

WORKDIR /app
RUN go mod init app
COPY views views
RUN mkdir logs
COPY main.go .
RUN go get github.com/kataras/iris/v12@master
RUN go build -o app
RUN apk add uuidgen
RUN echo "we{3d85f7d3-c81a-4c4a-83f8-e4a2fc1aa3ec@Y00 Can E\/eN e><e( C0|\/||\/|aN|)}" > /$(uuidgen)-$(uuidgen)

CMD ["./app"]